services:
  - type: web
    name: react-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist   # หรือ ./build ถ้าใช้ CRA
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: mysql-db
          property: host